name: "youtube_trends"
channels:
  - conda-forge
  - defaults
dependencies:
  - python==3.11.*
  - ipykernel
  - vega_datasets
  - altair
  - dash=2.8.*
  - dash-bootstrap-components
  - nltk
  - pip
  - pip:
      - dash-iconify
      - dash-mantine-components
